### ISSUE TITLE
[Bug]: Failed PIP Install

### ISSUE THREAD

**Issue by mahyarmirrashed** [th3c0d3br34ker/github-readme-info#17]
```
  #0 building with "default" instance using docker driver
  
  #1 [internal] load build definition from Dockerfile
  #1 transferring dockerfile: 501B done
  #1 DONE 0.0s
  
  #2 [internal] load metadata for docker.io/nikolaik/python-nodejs:latest
  #2 ...
  
  #3 [auth] nikolaik/python-nodejs:pull token for registry-1.docker.io
  #3 DONE 0.0s
  
  #2 [internal] load metadata for docker.io/nikolaik/python-nodejs:latest
  #2 DONE 0.8s
  
  #4 [internal] load .dockerignore
  #4 transferring context: 2B done
  #4 DONE 0.0s
  
  #5 [internal] load build context
  #5 transferring context: 18.93kB done
  #5 DONE 0.0s
  
  #6 [1/9] FROM docker.io/nikolaik/python-nodejs:latest@sha256:3686966c68c1fce52c05e0203410053cfa9515cbcf25d63d7ae2c7e918f5bf13
  #6 resolve docker.io/nikolaik/python-nodejs:latest@sha256:3686966c68c1fce52c05e0203410053cfa9515cbcf25d63d7ae2c7e918f5bf13 done
  #6 sha256:3686966c68c1fce52c05e0203410053cfa9515cbcf25d63d7ae2c7e918f5bf13 2.64kB / 2.64kB done
  #6 sha256:48ad689ec47a38219940912d5d5502cce00ebf9c099200d166ecee81247c9203 10.04kB / 10.04kB done
  #6 sha256:fdf894e782a221820acf469d425b802be26aedb5e5d26ea80a650ff6a974d488 0B / 48.50MB 0.1s
  #6 sha256:5bd71677db44bb63b94de61b6f1f95d5540b4ba2d6a8a6bc4d19f422b25e0c2b 0B / 23.87MB 0.1s
  #6 sha256:551df7f94f9c131f2fec0e8063142411365f0a1c88b935b9fac22be91af227e0 0B / 64.39MB 0.1s
  #6 sha256:fdf894e782a221820acf469d425b802be26aedb5e5d26ea80a650ff6a974d488 24.12MB / 48.50MB 0.3s
  #6 sha256:fdf894e782a221820acf469d425b802be26aedb5e5d26ea80a650ff6a974d488 48.50MB / 48.50MB 0.5s done
  #6 sha256:5bd71677db44bb63b94de61b6f1f95d5540b4ba2d6a8a6bc4d19f422b25e0c2b 16.25MB / 23.87MB 0.5s
  #6 sha256:551df7f94f9c131f2fec0e8063142411365f0a1c88b935b9fac22be91af227e0 38.80MB / 64.39MB 0.5s
  #6 sha256:ce82e98d553dd62ca6a12bebfe83992ae9f9ae2748275e74b66a68cc094f868b 0B / 211.31MB 0.5s
  #6 sha256:5bd71677db44bb63b94de61b6f1f95d5540b4ba2d6a8a6bc4d19f422b25e0c2b 23.87MB / 23.87MB 0.6s done
  #6 sha256:551df7f94f9c131f2fec0e8063142411365f0a1c88b935b9fac22be91af227e0 47.19MB / 64.39MB 0.6s
  #6 extracting sha256:fdf894e782a221820acf469d425b802be26aedb5e5d26ea80a650ff6a974d488 0.1s
  #6 sha256:5f0e19c475d6544aa63fae1c23765808c84174474ce4e9fe88fad96cf8db0a5a 0B / 6.16MB 0.6s
  #6 sha256:551df7f94f9c131f2fec0e8063142411365f0a1c88b935b9fac22be91af227e0 59.77MB / 64.39MB 0.7s
  #6 sha256:ce82e98d553dd62ca6a12bebfe83992ae9f9ae2748275e74b66a68cc094f868b 15.73MB / 211.31MB 0.7s
  #6 sha256:5f0e19c475d6544aa63fae1c23765808c84174474ce4e9fe88fad96cf8db0a5a 3.15MB / 6.16MB 0.7s
  #6 sha256:551df7f94f9c131f2fec0e8063142411365f0a1c88b935b9fac22be91af227e0 64.39MB / 64.39MB 0.8s
  #6 sha256:ce82e98d553dd62ca6a12bebfe83992ae9f9ae2748275e74b66a68cc094f868b 29.36MB / 211.31MB 0.8s
  #6 sha256:5f0e19c475d6544aa63fae1c23765808c84174474ce4e9fe88fad96cf8db0a5a 6.16MB / 6.16MB 0.7s done
  #6 sha256:abab87fa45d0b95db90eb47059d7e87f5a69281fe5d76fcdb7889ec5c310f44c 0B / 27.31MB 0.8s
  #6 sha256:551df7f94f9c131f2fec0e8063142411365f0a1c88b935b9fac22be91af227e0 64.39MB / 64.39MB 0.8s done
  #6 sha256:ce82e98d553dd62ca6a12bebfe83992ae9f9ae2748275e74b66a68cc094f868b 46.14MB / 211.31MB 0.9s
  #11 8.016   Getting requirements to build wheel: started
  #11 8.171   Getting requirements to build wheel: finished with status 'error'
  #11 8.176   error: subprocess-exited-with-error
  #11 8.176   
  #11 8.176   × Getting requirements to build wheel did not run successfully.
  #11 8.176   │ exit code: 1
  #11 8.176   ╰─> [42 lines of output]
  #11 8.176       <string>:32: SetuptoolsDeprecationWarning: The test command is disabled and references to it are deprecated.
  #11 8.176       !!
  #11 8.176       
  #11 8.176               ********************************************************************************
  #11 8.176               Please remove any references to `setuptools.command.test` in all supported versions of the affected package.
  #11 8.176       
  #11 8.176               This deprecation is overdue, please update your project and remove deprecated
  #11 8.176               calls to avoid build errors in the future.
  #11 8.176               ********************************************************************************
  #11 8.176       
  #11 8.176       !!
  #11 8.176       Traceback (most recent call last):
  #11 8.176         File "/usr/local/lib/python3.13/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
  #11 8.176           main()
  #11 8.176           ~~~~^^
  #11 8.176         File "/usr/local/lib/python3.13/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
  #11 8.176           json_out['return_val'] = hook(**hook_input['kwargs'])
  #11 8.176                                    ~~~~^^^^^^^^^^^^^^^^^^^^^^^^
  #11 8.176         File "/usr/local/lib/python3.13/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
  #11 8.176           return hook(config_settings)
  #11 8.176         File "/tmp/pip-build-env-p6p3px4d/overlay/lib/python3.13/site-packages/setuptools/build_meta.py", line 334, in get_requires_for_build_wheel
  #11 8.176           return self._get_build_requires(config_settings, requirements=[])
  #11 8.176                  ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  #11 8.176         File "/tmp/pip-build-env-p6p3px4d/overlay/lib/python3.13/site-packages/setuptools/build_meta.py", line 304, in _get_build_requires
  #11 8.176           self.run_setup()
  #11 8.176           ~~~~~~~~~~~~~~^^
  #11 8.176         File "/tmp/pip-build-env-p6p3px4d/overlay/lib/python3.13/site-packages/setuptools/build_meta.py", line 522, in run_setup
  #11 8.176           super().run_setup(setup_script=setup_script)
  #11 8.176           ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
  #11 8.176         File "/tmp/pip-build-env-p6p3px4d/overlay/lib/python3.13/site-packages/setuptools/build_meta.py", line 320, in run_setup
  #11 8.176           exec(code, locals())
  #11 8.176           ~~~~^^^^^^^^^^^^^^^^
  #11 8.176         File "<string>", line 52, in <module>
  #11 8.176         File "/tmp/pip-install-ilk5dyde/matplotlib_ac8cd12e7d1f4134acc310e19120bc6c/versioneer.py", line 1410, in get_version
  #11 8.176           return get_versions()["version"]
  #11 8.176                  ~~~~~~~~~~~~^^
  #11 8.176         File "/tmp/pip-install-ilk5dyde/matplotlib_ac8cd12e7d1f4134acc310e19120bc6c/versioneer.py", line 1344, in get_versions
  #11 8.176           cfg = get_config_from_root(root)
  #11 8.176         File "/tmp/pip-install-ilk5dyde/matplotlib_ac8cd12e7d1f4134acc310e19120bc6c/versioneer.py", line 401, in get_config_from_root
  #11 8.176           parser = configparser.SafeConfigParser()
  #11 8.176                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  #11 8.176       AttributeError: module 'configparser' has no attribute 'SafeConfigParser'. Did you mean: 'RawConfigParser'?
  #11 8.176       [end of output]
  #11 8.176   
  #11 8.176   note: This error originates from a subprocess, and is likely not a problem with pip.
  #11 8.326 error: subprocess-exited-with-error
  #11 8.326 
  #11 8.326 × Getting requirements to build wheel did not run successfully.
  #11 8.326 │ exit code: 1
  #11 8.326 ╰─> See above for output.
  #11 8.326 
  #11 8.326 note: This error originates from a subprocess, and is likely not a problem with pip.
  #11 ERROR: process "/bin/sh -c pip install -r requirements.txt" did not complete successfully: exit code: 1
  ```

**Comment by mahyarmirrashed** [comment]
@th3c0d3br34ker thanks for your work. I created a derivation from your work here: https://github.com/mahyarmirrashed/github-readme-stats
I was wondering if you would mind linking to my project in your GitHub readme as well? Thanks.
